name: Domain Configuration UI
description: 'Allows saving of domain specific configuration through the UI.'
type: module
package: Domain
core: 8.x
configure: domain_config_ui.settings
dependencies:
  - domain:domain_config
