# Schema for the configuration files of the Domain Config UI module.
domain_config_ui.settings:
  type: config_object
  label: 'Domain Config UI settings'
  mapping:
    remember_domain:
      type: boolean
      label: 'Remember domain selection'
    path_pages:
      type: text
      label: 'Paths for supported configuration forms'
